export const REQUEST_IMAGE_ANALYSIS = 'REQUEST_IMAGE_ANALYSIS';
export const RECEIVE_IMAGE_ANALYSIS = 'RECEIVE_IMAGE_ANALYSIS';
export const REJECT_IMAGE_ANALYSIS = 'REJECT_IMAGE_ANALYSIS';

export const SELECT_FILE = 'SELECT_FILE';
export const UPDATE_FILE_SELECTION = 'UPDATE_FILE_SELECTION';
export const SELECT_VISUALIZATION_TARGET = 'SELECT_VISUALIZATION_TARGET';
export const SELECT_VISUALIZATION_LAYER = 'SELECT_VISUALIZATION_LAYER';

export const ATTACH_FILE = 'ATTACH_FILE';
export const DETACH_FILE = 'DETACH_FILE'; 
export const EDIT_FIELD = 'EDIT_FIELD';

export const REQUEST_FILE_UPLOAD = 'REQUEST_FILE_UPLOAD';

export const REQUEST_FILE_REFRESH = 'REQUEST_FILE_REFRESH';
export const RECEIVE_FILE_REFRESH = 'RECEIVE_FILE_REFRESH';
export const REJECT_FILE_REFRESH = 'REJECT_FILE_REFRESH';

export const SET_API_URL = 'SET_API_URL';

export const SELECT_CNN_LAYER = 'SELECT_CNN_LAYER';
export const SELECT_CNN_CLASS = 'SELECT_CNN_CLASS';

export const REQUEST_CNN_CLASSES = 'REQUEST_CNN_CLASSES';
export const REQUEST_CNN_LAYERS = 'REQUEST_CNN_LAYERS';

export const RECEIVE_CNN_CLASSES = 'RECEIVE_CNN_CLASSES';
export const RECEIVE_CNN_LAYERS = 'RECEIVE_CNN_LAYERS';

export const REQUEST_GRADCAM = 'REQUEST_GRADCAM';
export const RECEIVE_GRADCAM = 'RECEIVE_GRADCAM';

export const REQUEST_GUIDED_GRADCAM = 'REQUEST_GUIDED_GRADCAM';
export const RECEIVE_GUIDED_GRADCAM = 'RECEIVE_GUIDED_GRADCAM';

export const UPDATE_SELECTED_GUIDED_GRADCAM = 'UPDATE_SELECTED_GUIDED_GRADCAM';
export const UPDATE_SELECTED_GRADCAM = 'UPDATE_SELECTED_GRADCAM';

export const REQUEST_SELECTED_GRADCAM = 'REQUEST_SELECTED_GRADCAM';
export const REQUEST_SELECTED_GUIDED_GRADCAM = 'REQUEST_SELECTED_GUIDED_GRADCAM';

export const RECEIVE_SELECTED_VISUALIZATIONS = 'RECEIVE_SELECTED_VISUALIZATIONS';
export const REQUEST_SELECTED_VISUALIZATIONS = 'REQUEST_SELECTED_VISUALIZATIONS';
export const UPDATE_SELECTED_VISUALIZATIONS = 'UPDATE_SELECTED_VISUALIZATIONS';

export const REQUEST_CNN_CLASSIFICATION = 'REQUEST_CNN_CLASSIFICATION';
export const RECEIVE_CNN_CLASSIFICATION = 'RECEIVE_CNN_CLASSIFICATION';